#!/bin/bash

USER=`whoami`
HOSTNAME=`uname -n`

# Note: If you cannot resolve the hostname, use -I instead here!  I use lowercase to identify name resolution issues on login.
IP=`hostname -i`
ROOT=`df -Ph | grep root | awk '{print $4}' | tr -d '\n'`
HOME=`df -Ph | grep home | awk '{print $4}' | tr -d '\n'`
BACKUP=`df -Ph | grep backup | awk '{print $4}' | tr -d '\n'`

MEMORY=`free -m | grep "Mem" | awk '{print $2,"-",$3,"-",$4}'`
SWAP=`free -m | grep "Swap" | awk '{print $2,"-",$3,"-",$4}'`
PSA=`ps -Afl | wc -l`

# time of day
HOUR=$(TZ='America/Los_Angeles' date +"%H")
if [ $HOUR -lt 12  -a $HOUR -ge 0 ]
then    TIME="Morning"
elif [ $HOUR -lt 17 -a $HOUR -ge 12 ]
then    TIME="Afternoon"
else
    TIME="Evening"
fi

#System uptime
uptime=`cat /proc/uptime | cut -f1 -d.`
upDays=$((uptime/60/60/24))
upHours=$((uptime/60/60%24))
upMins=$((uptime/60%60))
upSecs=$((uptime%60))

#System load
LOAD1=`cat /proc/loadavg | awk {'print $1'}`
LOAD5=`cat /proc/loadavg | awk {'print $2'}`
LOAD15=`cat /proc/loadavg | awk {'print $3'}`

echo ""
echo -e "\e[33;1m--- Good $TIME $USER ----\e[0m"

COLOR_COLUMN="\e[33;1m-"
COLOR_VALUE="\e[33;40m"
RESET_COLORS="\e[0m"
echo -e "
===========================================================================
 $COLOR_COLUMN- Hostname$RESET_COLORS............: $COLOR_VALUE $HOSTNAME $RESET_COLORS
 $COLOR_COLUMN- IP Address$RESET_COLORS..........: $COLOR_VALUE $IP $RESET_COLORS
 $COLOR_COLUMN- Release$RESET_COLORS.............: $COLOR_VALUE `cat /etc/redhat-release` $RESET_COLORS
 $COLOR_COLUMN- Users$RESET_COLORS...............: $COLOR_VALUE Currently `users | wc -w` User(s) Logged on $RESET_COLORS
=========================================================================== $RESET_COLORS
 $COLOR_COLUMN- Current User$RESET_COLORS........: $COLOR_VALUE $USER $RESET_COLORS
 $COLOR_COLUMN- CPU Usage$RESET_COLORS...........: $COLOR_VALUE $LOAD1 - $LOAD5 - $LOAD15 (1-5-15) $RESET_COLORS
 $COLOR_COLUMN- Memory used$RESET_COLORS.........: $COLOR_VALUE $MEMORY (Total-Free-Used) $RESET_COLORS
 $COLOR_COLUMN- Swap in Use$RESET_COLORS.........: $COLOR_VALUE $SWAP (Total-Used-Free) MB $RESET_COLORS
 $COLOR_COLUMN- Processes$RESET_COLORS...........: $COLOR_VALUE $PSA Running Processes $RESET_COLORS
 $COLOR_COLUMN- System Uptime$RESET_COLORS.......: $COLOR_VALUE $upDays Days $upHours Hours $upMins Minutes $upSecs Seconds $RESET_COLORS
 $COLOR_COLUMN- Disk Space / $RESET_COLORS.......: $COLOR_VALUE $ROOT Remaining $RESET_COLORS
===========================================================================
"

echo "|~*~*~*~*~ All System Activity is Logged and Monitored. Be Aware of What You Are Doing! ~*~*~*~*~|"

echo ""